[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "anime-cli"
version = "1.0.0"
description = "A terminal anime player using VLC"
requires-python = ">=3.10"

[project.scripts]
anime = "anime.main:main"

dependencies = [
    "platformdirs",
    'windows-curses; platform_system == "Windows"',
]
