[project]
name = "anime-cli"
version = "0.1.0"
description = "A terminal-based anime player."
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "platformdirs",
    "windows-curses; platform_system == 'Windows'",
    "httpx",
    "requests"
]

[project.scripts]
anime = "anime.main:main"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["anime*"]
